### ISSUE TITLE
yaml2go produces duplicate structs

### ISSUE THREAD

**Issue by PrasadG193** [PrasadG193/yaml2go#19]
For yaml like:
```
key2:
  key: value
key3:
  key2:
    key: value
    key1: value
```
yaml2go produces
```
// Yaml2Go
type Yaml2Go struct {
        Key2 Key2 `yaml:"key2"`
        Key3 Key3 `yaml:"key3"`
}

// Key2
type Key2 struct {
        Key string `yaml:"key"`
}

// Key2
type Key2 struct {
        Key  string `yaml:"key"`
        Key1 string `yaml:"key1"`
}

// Key3
type Key3 struct {
        Key2 Key2 `yaml:"key2"`
}
```
which contains duplicate struct `Key2`
